### ISSUE TITLE
Unable to use Private Key / Passphrase with SSH Connections

### ISSUE THREAD

**Issue by Arudinne** [paidem/guacozy#5]
Hello,

I have been trying to add some of our linux hosts to the guacozy instance i rolled out, however I get "CLIENT_UNAUTHORIZED" when I try to connect. Here is the screenshot of the error from the first server I have tried adding:

![image](https://user-images.githubusercontent.com/29390020/68323999-25557380-008c-11ea-9353-f022337410c0.png)

This is a freshly deployed linux host and I am able to connect just fine with putty (via pagent) using the same private key/passphrase

**Comment by paidem** [comment]
I checked with a linux host - generated two keys in linux (ssh-keygen) - one without passphrase and one with passphrase. Both worked for me. So this means that passing those parameters from guacozy to guacd works. I can get this error only in 3 cases: 
1. The certificate is wrong for this server/user combination 
2. Passphrase is wrong.
3. Username is wrong

To find the problem I would suggest following steps:

Double check if everything is entered correctly. 
Check that you enter password in 'passphrase' field ant not in 'password'
Check with another server. 
Generate new keys with/without password. 
Enter keys in RSA format (beginning with `-----BEGIN RSA PRIVATE KEY-----`)

Check logs of guacd (if you run docker-compose, you can `docker-compose logs guacd` or to follow logs `docker-compose logs -f guacd`)

**Comment by Arudinne** [comment]
Looks like the key I was given was not in RSA format, but rather PPK format. My bad! 

Looks like it is working now if I add it directly the connection configuration, but not if configured using static credentials. I believe the documentation states this is currently an issue, correct?.

**Comment by paidem** [comment]
I have reproduced the problem and opened new issue (as it is different and will be easier to understand in commit reference).

**Comment by Arudinne** [comment]
Sounds good!

**Comment by paidem** [comment]
Fixed in v0.0.23. Builds will be available when dockerhub autobuild is finished (~30-40 min)
See tags here. https://hub.docker.com/r/guacozy/guacozy-server/tags
